// source: smart_plug.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.SmartPlug');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Field');
goog.require('proto.UUID');

goog.forwardDeclare('proto.SchemaVersion');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SmartPlug = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SmartPlug.repeatedFields_, null);
};
goog.inherits(proto.SmartPlug, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SmartPlug.displayName = 'proto.SmartPlug';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SmartPlug.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SmartPlug.prototype.toObject = function(opt_includeInstance) {
  return proto.SmartPlug.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SmartPlug} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SmartPlug.toObject = function(includeInstance, msg) {
  var f, obj = {
    timestamp: jspb.Message.getFieldWithDefault(msg, 1, 0),
    version: jspb.Message.getFieldWithDefault(msg, 2, 0),
    identity: (f = msg.getIdentity()) && proto.UUID.toObject(includeInstance, f),
    fieldsList: jspb.Message.toObjectList(msg.getFieldsList(),
    proto.Field.toObject, includeInstance),
    sequence: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SmartPlug}
 */
proto.SmartPlug.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SmartPlug;
  return proto.SmartPlug.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SmartPlug} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SmartPlug}
 */
proto.SmartPlug.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {!proto.SchemaVersion} */ (reader.readEnum());
      msg.setVersion(value);
      break;
    case 3:
      var value = new proto.UUID;
      reader.readMessage(value,proto.UUID.deserializeBinaryFromReader);
      msg.setIdentity(value);
      break;
    case 4:
      var value = new proto.Field;
      reader.readMessage(value,proto.Field.deserializeBinaryFromReader);
      msg.addFields(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSequence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SmartPlug.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SmartPlug.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SmartPlug} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SmartPlug.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getIdentity();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.UUID.serializeBinaryToWriter
    );
  }
  f = message.getFieldsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.Field.serializeBinaryToWriter
    );
  }
  f = message.getSequence();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
};


/**
 * optional uint64 timestamp = 1;
 * @return {number}
 */
proto.SmartPlug.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SmartPlug} returns this
 */
proto.SmartPlug.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional SchemaVersion version = 2;
 * @return {!proto.SchemaVersion}
 */
proto.SmartPlug.prototype.getVersion = function() {
  return /** @type {!proto.SchemaVersion} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.SchemaVersion} value
 * @return {!proto.SmartPlug} returns this
 */
proto.SmartPlug.prototype.setVersion = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional UUID identity = 3;
 * @return {?proto.UUID}
 */
proto.SmartPlug.prototype.getIdentity = function() {
  return /** @type{?proto.UUID} */ (
    jspb.Message.getWrapperField(this, proto.UUID, 3));
};


/**
 * @param {?proto.UUID|undefined} value
 * @return {!proto.SmartPlug} returns this
*/
proto.SmartPlug.prototype.setIdentity = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SmartPlug} returns this
 */
proto.SmartPlug.prototype.clearIdentity = function() {
  return this.setIdentity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SmartPlug.prototype.hasIdentity = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated Field fields = 4;
 * @return {!Array<!proto.Field>}
 */
proto.SmartPlug.prototype.getFieldsList = function() {
  return /** @type{!Array<!proto.Field>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Field, 4));
};


/**
 * @param {!Array<!proto.Field>} value
 * @return {!proto.SmartPlug} returns this
*/
proto.SmartPlug.prototype.setFieldsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.Field=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Field}
 */
proto.SmartPlug.prototype.addFields = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.Field, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SmartPlug} returns this
 */
proto.SmartPlug.prototype.clearFieldsList = function() {
  return this.setFieldsList([]);
};


/**
 * optional uint64 sequence = 5;
 * @return {number}
 */
proto.SmartPlug.prototype.getSequence = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.SmartPlug} returns this
 */
proto.SmartPlug.prototype.setSequence = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


