/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: smart_plug.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "smart_plug.pb-c.h"
void   power__init
                     (Power         *message)
{
  static const Power init_value = POWER__INIT;
  *message = init_value;
}
size_t power__get_packed_size
                     (const Power *message)
{
  assert(message->base.descriptor == &power__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t power__pack
                     (const Power *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &power__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t power__pack_to_buffer
                     (const Power *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &power__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Power *
       power__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Power *)
     protobuf_c_message_unpack (&power__descriptor,
                                allocator, len, data);
}
void   power__free_unpacked
                     (Power *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &power__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   field__init
                     (Field         *message)
{
  static const Field init_value = FIELD__INIT;
  *message = init_value;
}
size_t field__get_packed_size
                     (const Field *message)
{
  assert(message->base.descriptor == &field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field__pack
                     (const Field *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field__pack_to_buffer
                     (const Field *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Field *
       field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Field *)
     protobuf_c_message_unpack (&field__descriptor,
                                allocator, len, data);
}
void   field__free_unpacked
                     (Field *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uuid__init
                     (UUID         *message)
{
  static const UUID init_value = UUID__INIT;
  *message = init_value;
}
size_t uuid__get_packed_size
                     (const UUID *message)
{
  assert(message->base.descriptor == &uuid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uuid__pack
                     (const UUID *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uuid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uuid__pack_to_buffer
                     (const UUID *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uuid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UUID *
       uuid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UUID *)
     protobuf_c_message_unpack (&uuid__descriptor,
                                allocator, len, data);
}
void   uuid__free_unpacked
                     (UUID *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uuid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smart_plug__init
                     (SmartPlug         *message)
{
  static const SmartPlug init_value = SMART_PLUG__INIT;
  *message = init_value;
}
size_t smart_plug__get_packed_size
                     (const SmartPlug *message)
{
  assert(message->base.descriptor == &smart_plug__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smart_plug__pack
                     (const SmartPlug *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smart_plug__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smart_plug__pack_to_buffer
                     (const SmartPlug *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smart_plug__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmartPlug *
       smart_plug__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmartPlug *)
     protobuf_c_message_unpack (&smart_plug__descriptor,
                                allocator, len, data);
}
void   smart_plug__free_unpacked
                     (SmartPlug *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &smart_plug__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor power__field_descriptors[4] =
{
  {
    "voltage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Power, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Power, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Power, power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Power, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned power__field_indices_by_name[] = {
  1,   /* field[1] = current */
  2,   /* field[2] = power */
  3,   /* field[3] = timestamp */
  0,   /* field[0] = voltage */
};
static const ProtobufCIntRange power__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor power__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Power",
  "Power",
  "Power",
  "",
  sizeof(Power),
  4,
  power__field_descriptors,
  power__field_indices_by_name,
  1,  power__number_ranges,
  (ProtobufCMessageInit) power__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor field__field_descriptors[17] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Field, key),
    &field_key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_bool",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Field, value_case),
    offsetof(Field, v_bool),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_int32",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Field, value_case),
    offsetof(Field, v_int32),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_uint32",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Field, value_case),
    offsetof(Field, v_uint32),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_sint32",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Field, value_case),
    offsetof(Field, v_sint32),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_fixed32",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Field, value_case),
    offsetof(Field, v_fixed32),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_sfixed32",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SFIXED32,
    offsetof(Field, value_case),
    offsetof(Field, v_sfixed32),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_int64",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Field, value_case),
    offsetof(Field, v_int64),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_uint64",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Field, value_case),
    offsetof(Field, v_uint64),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_sint64",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Field, value_case),
    offsetof(Field, v_sint64),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_fixed64",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(Field, value_case),
    offsetof(Field, v_fixed64),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_sfixed64",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SFIXED64,
    offsetof(Field, value_case),
    offsetof(Field, v_sfixed64),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_double",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Field, value_case),
    offsetof(Field, v_double),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_float",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Field, value_case),
    offsetof(Field, v_float),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_string",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Field, value_case),
    offsetof(Field, v_string),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_bytes",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Field, value_case),
    offsetof(Field, v_bytes),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_power",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Field, value_case),
    offsetof(Field, v_power),
    &power__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = v_bool */
  15,   /* field[15] = v_bytes */
  12,   /* field[12] = v_double */
  5,   /* field[5] = v_fixed32 */
  10,   /* field[10] = v_fixed64 */
  13,   /* field[13] = v_float */
  2,   /* field[2] = v_int32 */
  7,   /* field[7] = v_int64 */
  16,   /* field[16] = v_power */
  6,   /* field[6] = v_sfixed32 */
  11,   /* field[11] = v_sfixed64 */
  4,   /* field[4] = v_sint32 */
  9,   /* field[9] = v_sint64 */
  14,   /* field[14] = v_string */
  3,   /* field[3] = v_uint32 */
  8,   /* field[8] = v_uint64 */
};
static const ProtobufCIntRange field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Field",
  "Field",
  "Field",
  "",
  sizeof(Field),
  17,
  field__field_descriptors,
  field__field_indices_by_name,
  1,  field__number_ranges,
  (ProtobufCMessageInit) field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uuid__field_descriptors[1] =
{
  {
    "devId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UUID, devid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uuid__field_indices_by_name[] = {
  0,   /* field[0] = devId */
};
static const ProtobufCIntRange uuid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor uuid__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UUID",
  "UUID",
  "UUID",
  "",
  sizeof(UUID),
  1,
  uuid__field_descriptors,
  uuid__field_indices_by_name,
  1,  uuid__number_ranges,
  (ProtobufCMessageInit) uuid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smart_plug__field_descriptors[5] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(SmartPlug, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SmartPlug, version),
    &schema_version__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "identity",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SmartPlug, identity),
    &uuid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fields",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SmartPlug, n_fields),
    offsetof(SmartPlug, fields),
    &field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(SmartPlug, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smart_plug__field_indices_by_name[] = {
  3,   /* field[3] = fields */
  2,   /* field[2] = identity */
  4,   /* field[4] = sequence */
  0,   /* field[0] = timestamp */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange smart_plug__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor smart_plug__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SmartPlug",
  "SmartPlug",
  "SmartPlug",
  "",
  sizeof(SmartPlug),
  5,
  smart_plug__field_descriptors,
  smart_plug__field_indices_by_name,
  1,  smart_plug__number_ranges,
  (ProtobufCMessageInit) smart_plug__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue schema_version__enum_values_by_number[2] =
{
  { "INVALID", "SCHEMA_VERSION__INVALID", 0 },
  { "SMARTPLUG_V1", "SCHEMA_VERSION__SMARTPLUG_V1", 1 },
};
static const ProtobufCIntRange schema_version__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex schema_version__enum_values_by_name[2] =
{
  { "INVALID", 0 },
  { "SMARTPLUG_V1", 1 },
};
const ProtobufCEnumDescriptor schema_version__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SchemaVersion",
  "SchemaVersion",
  "SchemaVersion",
  "",
  2,
  schema_version__enum_values_by_number,
  2,
  schema_version__enum_values_by_name,
  1,
  schema_version__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue field_key__enum_values_by_number[3] =
{
  { "UNUSED", "FIELD_KEY__UNUSED", 0 },
  { "FW_INFORMATION", "FIELD_KEY__FW_INFORMATION", 1 },
  { "POWER", "FIELD_KEY__POWER", 2 },
};
static const ProtobufCIntRange field_key__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex field_key__enum_values_by_name[3] =
{
  { "FW_INFORMATION", 1 },
  { "POWER", 2 },
  { "UNUSED", 0 },
};
const ProtobufCEnumDescriptor field_key__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FieldKey",
  "FieldKey",
  "FieldKey",
  "",
  3,
  field_key__enum_values_by_number,
  3,
  field_key__enum_values_by_name,
  1,
  field_key__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
