# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart_plug.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smart_plug.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10smart_plug.proto\"K\n\x05Power\x12\x0f\n\x07voltage\x18\x01 \x01(\r\x12\x0f\n\x07\x63urrent\x18\x02 \x01(\r\x12\r\n\x05power\x18\x03 \x01(\r\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\"\xef\x02\n\x05\x46ield\x12\x16\n\x03key\x18\x01 \x01(\x0e\x32\t.FieldKey\x12\x10\n\x06v_bool\x18\x02 \x01(\x08H\x00\x12\x11\n\x07v_int32\x18\x03 \x01(\x05H\x00\x12\x12\n\x08v_uint32\x18\x04 \x01(\rH\x00\x12\x12\n\x08v_sint32\x18\x05 \x01(\x11H\x00\x12\x13\n\tv_fixed32\x18\x06 \x01(\x07H\x00\x12\x14\n\nv_sfixed32\x18\x07 \x01(\x0fH\x00\x12\x11\n\x07v_int64\x18\x08 \x01(\x03H\x00\x12\x12\n\x08v_uint64\x18\t \x01(\x04H\x00\x12\x12\n\x08v_sint64\x18\n \x01(\x12H\x00\x12\x13\n\tv_fixed64\x18\x0b \x01(\x06H\x00\x12\x14\n\nv_sfixed64\x18\x0c \x01(\x10H\x00\x12\x12\n\x08v_double\x18\r \x01(\x01H\x00\x12\x11\n\x07v_float\x18\x0e \x01(\x02H\x00\x12\x12\n\x08v_string\x18\x0f \x01(\tH\x00\x12\x11\n\x07v_bytes\x18\x10 \x01(\x0cH\x00\x12\x19\n\x07v_power\x18\x11 \x01(\x0b\x32\x06.PowerH\x00\x42\x07\n\x05value\"\x15\n\x04UUID\x12\r\n\x05\x64\x65vId\x18\x01 \x01(\t\"\x82\x01\n\tSmartPlug\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x1f\n\x07version\x18\x02 \x01(\x0e\x32\x0e.SchemaVersion\x12\x17\n\x08identity\x18\x03 \x01(\x0b\x32\x05.UUID\x12\x16\n\x06\x66ields\x18\x04 \x03(\x0b\x32\x06.Field\x12\x10\n\x08sequence\x18\x05 \x01(\x04*.\n\rSchemaVersion\x12\x0b\n\x07INVALID\x10\x00\x12\x10\n\x0cSMARTPLUG_V1\x10\x01*5\n\x08\x46ieldKey\x12\n\n\x06UNUSED\x10\x00\x12\x12\n\x0e\x46W_INFORMATION\x10\x01\x12\t\n\x05POWER\x10\x02\x62\x06proto3'
)

_SCHEMAVERSION = _descriptor.EnumDescriptor(
  name='SchemaVersion',
  full_name='SchemaVersion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SMARTPLUG_V1', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=623,
  serialized_end=669,
)
_sym_db.RegisterEnumDescriptor(_SCHEMAVERSION)

SchemaVersion = enum_type_wrapper.EnumTypeWrapper(_SCHEMAVERSION)
_FIELDKEY = _descriptor.EnumDescriptor(
  name='FieldKey',
  full_name='FieldKey',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNUSED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FW_INFORMATION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POWER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=671,
  serialized_end=724,
)
_sym_db.RegisterEnumDescriptor(_FIELDKEY)

FieldKey = enum_type_wrapper.EnumTypeWrapper(_FIELDKEY)
INVALID = 0
SMARTPLUG_V1 = 1
UNUSED = 0
FW_INFORMATION = 1
POWER = 2



_POWER = _descriptor.Descriptor(
  name='Power',
  full_name='Power',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='voltage', full_name='Power.voltage', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current', full_name='Power.current', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power', full_name='Power.power', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Power.timestamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=95,
)


_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Field.key', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_bool', full_name='Field.v_bool', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_int32', full_name='Field.v_int32', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_uint32', full_name='Field.v_uint32', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_sint32', full_name='Field.v_sint32', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_fixed32', full_name='Field.v_fixed32', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_sfixed32', full_name='Field.v_sfixed32', index=6,
      number=7, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_int64', full_name='Field.v_int64', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_uint64', full_name='Field.v_uint64', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_sint64', full_name='Field.v_sint64', index=9,
      number=10, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_fixed64', full_name='Field.v_fixed64', index=10,
      number=11, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_sfixed64', full_name='Field.v_sfixed64', index=11,
      number=12, type=16, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_double', full_name='Field.v_double', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_float', full_name='Field.v_float', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_string', full_name='Field.v_string', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_bytes', full_name='Field.v_bytes', index=15,
      number=16, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_power', full_name='Field.v_power', index=16,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='Field.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=98,
  serialized_end=465,
)


_UUID = _descriptor.Descriptor(
  name='UUID',
  full_name='UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devId', full_name='UUID.devId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=488,
)


_SMARTPLUG = _descriptor.Descriptor(
  name='SmartPlug',
  full_name='SmartPlug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SmartPlug.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='SmartPlug.version', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identity', full_name='SmartPlug.identity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='SmartPlug.fields', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='SmartPlug.sequence', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=621,
)

_FIELD.fields_by_name['key'].enum_type = _FIELDKEY
_FIELD.fields_by_name['v_power'].message_type = _POWER
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_bool'])
_FIELD.fields_by_name['v_bool'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_int32'])
_FIELD.fields_by_name['v_int32'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_uint32'])
_FIELD.fields_by_name['v_uint32'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_sint32'])
_FIELD.fields_by_name['v_sint32'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_fixed32'])
_FIELD.fields_by_name['v_fixed32'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_sfixed32'])
_FIELD.fields_by_name['v_sfixed32'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_int64'])
_FIELD.fields_by_name['v_int64'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_uint64'])
_FIELD.fields_by_name['v_uint64'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_sint64'])
_FIELD.fields_by_name['v_sint64'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_fixed64'])
_FIELD.fields_by_name['v_fixed64'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_sfixed64'])
_FIELD.fields_by_name['v_sfixed64'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_double'])
_FIELD.fields_by_name['v_double'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_float'])
_FIELD.fields_by_name['v_float'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_string'])
_FIELD.fields_by_name['v_string'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_bytes'])
_FIELD.fields_by_name['v_bytes'].containing_oneof = _FIELD.oneofs_by_name['value']
_FIELD.oneofs_by_name['value'].fields.append(
  _FIELD.fields_by_name['v_power'])
_FIELD.fields_by_name['v_power'].containing_oneof = _FIELD.oneofs_by_name['value']
_SMARTPLUG.fields_by_name['version'].enum_type = _SCHEMAVERSION
_SMARTPLUG.fields_by_name['identity'].message_type = _UUID
_SMARTPLUG.fields_by_name['fields'].message_type = _FIELD
DESCRIPTOR.message_types_by_name['Power'] = _POWER
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['UUID'] = _UUID
DESCRIPTOR.message_types_by_name['SmartPlug'] = _SMARTPLUG
DESCRIPTOR.enum_types_by_name['SchemaVersion'] = _SCHEMAVERSION
DESCRIPTOR.enum_types_by_name['FieldKey'] = _FIELDKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Power = _reflection.GeneratedProtocolMessageType('Power', (_message.Message,), {
  'DESCRIPTOR' : _POWER,
  '__module__' : 'smart_plug_pb2'
  # @@protoc_insertion_point(class_scope:Power)
  })
_sym_db.RegisterMessage(Power)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), {
  'DESCRIPTOR' : _FIELD,
  '__module__' : 'smart_plug_pb2'
  # @@protoc_insertion_point(class_scope:Field)
  })
_sym_db.RegisterMessage(Field)

UUID = _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), {
  'DESCRIPTOR' : _UUID,
  '__module__' : 'smart_plug_pb2'
  # @@protoc_insertion_point(class_scope:UUID)
  })
_sym_db.RegisterMessage(UUID)

SmartPlug = _reflection.GeneratedProtocolMessageType('SmartPlug', (_message.Message,), {
  'DESCRIPTOR' : _SMARTPLUG,
  '__module__' : 'smart_plug_pb2'
  # @@protoc_insertion_point(class_scope:SmartPlug)
  })
_sym_db.RegisterMessage(SmartPlug)


# @@protoc_insertion_point(module_scope)
